services:
  relay:
    build:
      context: .
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
    expose:
      - "2947"
    ports:
      - "2947:2947"
    # network_mode: host
